image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-hiring-service:
  stage: build
  script:
    gradle hiring-service:assemble hiring-service:testClasses

checkStyle-hiring-service:
  stage: staticAnalysis
  script:
    gradle hiring-service:checkstyleMain hiring-service:checkStyleTest
  allow_failure: true

PMD-hiring-service:
  stage: staticAnalysis
  script:
      gradle hiring-service:pmdMain
  allow_failure: true

test-hiring-service:
  stage: test
  script:
    - gradle hiring-service:test hiring-service:jacocoTestReport
    - cat server/build/reports/jacoco/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
