image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

build-ta-service:
  stage: build
  script:
    gradle build

checkStyle-ta-service:
  stage: staticAnalysis
  script:
    gradle checkstyleMain checkStyleTest

PMD-ta-service:
  stage: staticAnalysis
  script:
      gradle pmdMain

test-ta-service:
  stage: test
  script:
    gradle test
