image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-ta-service:
  stage: build
  script:
    gradle ta-service:assemble ta-service:testClasses

checkStyle-ta-service:
  stage: staticAnalysis
  script:
    gradle ta-service:checkstyleMain ta-service:checkStyleTest
  allow_failure: true

PMD-ta-service:
  stage: staticAnalysis
  script:
      gradle ta-service:pmdMain
  allow_failure: true

test-ta-service:
  stage: test
  script:
    - gradle ta-service:test ta-service:jacocoTestReport
    - cat ta-service/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
