image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

build-course-service:
  stage: build
  script:
    gradle build

checkStyle-course-service:
  stage: staticAnalysis
  script:
    gradle checkstyleMain checkStyleTest

PMD-course-service:
  stage: staticAnalysis
  script:
      gradle pmdMain

test-course-service:
  stage: test
  script:
    gradle test
