image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-course-service:
  stage: build
  script:
    gradle course-service:assemble course-service:testClasses

checkStyle-course-service:
  stage: staticAnalysis
  script:
    gradle course-service:checkstyleMain course-service:checkStyleTest
  allow_failure: true


PMD-course-service:
  stage: staticAnalysis
  script:
    gradle course-service:pmdMain
  allow_failure: true

test-course-service:
  stage: test
  script:
    - gradle course-service:test course-service:jacocoTestReport
    - cat course-service/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
