image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-ta-microservice:
  stage: build
  script:
    gradle ta-microservice:assemble ta-microservice:testClasses

checkStyle-ta-microservice:
  stage: staticAnalysis
  script:
    gradle ta-microservice:checkstyleMain ta-microservice:checkStyleTest
  allow_failure: true

PMD-ta-microservice:
  stage: staticAnalysis
  script:
      gradle ta-microservice:pmdMain
  allow_failure: true

test-ta-microservice:
  stage: test
  script:
    - gradle ta-microservice:test ta-microservice:jacocoTestReport
    - cat ta-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
