image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-course-microservice:
  stage: build
  script:
    gradle course-microservice:assemble course-microservice:testClasses

checkStyle-course-microservice:
  stage: staticAnalysis
  script:
    gradle course-microservice:checkstyleMain course-microservice:checkStyleTest
  allow_failure: true


PMD-course-microservice:
  stage: staticAnalysis
  script:
    gradle course-microservice:pmdMain
  allow_failure: true

test-course-microservice:
  stage: test
  script:
    - gradle course-microservice:test course-microservice:jacocoTestReport
    - cat course-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
